# based on Genc Tato's docker-compose
version: '3.7'
services:
    web:
        #command: ["bash", "app.sh"]
        restart: always

        image: grosinosky/overleaf-web-nginx
        build: 
            #context: .
            #dockerfile: Dockerfile-web
            context: .
            dockerfile: server-ce/Dockerfile-webonly
            network: host

        # container_name: sharelatex-web
        depends_on:
            - redis
            - mongo
        privileged: true
        ports:
            - 8080:80 # nginx -> web & real-time 
        volumes: 
            # these files should be set together (or else 00_regen_sharelatex_secrets will replace them!)
            - ./WEB_API_PASSWORD:/etc/container_environment/WEB_API_PASSWORD # contains "password"
            - ./CRYPTO_RANDOM:/etc/container_environment/CRYPTO_RANDOM # contains 
        env_file:
            - default_ms.env
        environment:
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_REDIS_HOST: redis

            APP_NAME: MicroSharedLatex
            SHARELATEX_SESSION_SECRET: 'secret-please-change'
            PUBLIC_URL: http://localhost:8080/
            
            ENABLE_TRACE_AGENT: "true"
            ENABLE_DEBUG_AGENT: "true"
            LOG_LEVEL: "debug"
            DEBUG_NODE: 'true'

            SHARELATEX_APP_NAME: Overleaf Community Edition

            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
            WEB_API_PASSWORD: password
        networks:
            default:
                aliases:
                    - web
      
    clsi:
        restart: always
        image: grosinosky/overleaf-clsi
        #build: services/clsi
        build: 
            context: .
            dockerfile: Dockerfile-clsi
            network: host
        # container_name: sharelatex-clsi
        # expose:
        #     - 3013
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
            OPTIMISE_PDF: "true"

        ports:
            - 3013:3013

    filestore:
        restart: always
        image: grosinosky/overleaf-filestore
        build: services/filestore
        volumes:
            - ~/overleaf_data/filestore:/app/data
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
        ports:
            - 3009:3009
        

    docstore:
        restart: always
        image: grosinosky/overleaf-docstore
        build: services/docstore
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
        ports:
            - 3016:3016

    notifications:
        restart: always
        image: grosinosky/overleaf-notifications
        build: services/notifications
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
        ports:
            - 3042:3042

    contacts:
        restart: always
        image: grosinosky/overleaf-contacts
        build: services/contacts
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
        ports:
            - 3036:3036
        
    spelling:
        restart: always
        image: grosinosky/overleaf-spelling
        build: services/spelling
        ports:
            - 3005:3005
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo

    chat:
        restart: always
        image: grosinosky/overleaf-chat
        build: services/chat
        ports:
            - 3010:3010
        networks:
            default:
                aliases:
                    - chat
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo

    track-changes:
        restart: always
        image: grosinosky/overleaf-track-changes
        build: services/track-changes
        ports:
            - 3015:3015
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - track-changes
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo

    real-time:
        restart: always
        image: grosinosky/overleaf-real-time
        build: services/real-time
        ports:
            - 3026:3026
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - real-time
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
            LISTEN_ADDRESS: 0.0.0.0
            SESSION_SECRET: "secret-please-change"
            CONTINUAL_PUBSUB_TRAFFIC: "true"
            PUBLISH_ON_INDIVIDUAL_CHANNELS: "true"

    document-updater:
        restart: always
        image: grosinosky/overleaf-document-updater
        build: services/document-updater
        ports:
            - 3003:3003
        depends_on:
            - redis
        networks:
            default:
                aliases:
                    - document-updater
        env_file:
            - default_ms.env
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
            LISTEN_ADDRESS: 0.0.0.0

    mongo:
        restart: always
        image: mongo:4.2
        ports:
            - 27017:27017
        volumes:
            - ~/overleaf_data/mongo_data:/data/db

    redis:
        restart: always
        image: redis:5
        ports:
            - 6379:6379
        volumes:
            - ~/overleaf_data/redis_data:/data
        networks:
            default:
                aliases:
                    - redis
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo

        ports:
            - 8081:8081
    
    redis-ui:
        image: rediscommander/redis-commander
        environment:
            - REDIS_HOSTS=redis1:redis:6379
        ports:
            - 8082:8081  
networks:
    default:   
    

